export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART:"ADD_TO_CART",
    INCREASE_PRODUCT_QUANTITY:"INCREASE_PRODUCT_QUANTITY",
    DECREASE_PRODUCT_QUANTITY:"DECREASE_PRODUCT_QUANTITY",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    EMPTY_CART: "EMPTY_CART",
  };